const posters = {
  products: [
    {
      id: 1,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 82,
      discountPercentage: 12.52,
      rating: 4.73,
      size: '30x30',
      stock: 94,
      category: 'Abstract',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting-2.png'],
    },
    {
      id: 2,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 103,
      discountPercentage: 18.46,
      rating: 4.49,
      size: '40x40',
      stock: 34,
      category: 'Nature',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting-2.png'],
    },
    {
      id: 3,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 79,
      discountPercentage: 15.46,
      rating: 4.15,
      size: '30x30',
      stock: 36,
      category: 'Romantic',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting-2.png'],
    },
    {
      id: 4,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 107,
      discountPercentage: 17.9,
      rating: 4.33,
      size: '40x40',
      stock: 123,
      category: 'Space',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 5,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 82,
      discountPercentage: 10.55,
      rating: 4.23,
      size: '30x30',
      stock: 32,
      category: 'Urban',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 6,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 75,
      discountPercentage: 11.89,
      rating: 4.6,
      size: '30x30',
      stock: 83,
      category: 'Characters',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 7,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 103,
      discountPercentage: 4.14,
      rating: 4.21,
      size: '40x40',
      stock: 50,
      category: 'Abstract',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 8,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 85,
      discountPercentage: 10.2,
      rating: 4.47,
      size: '30x30',
      stock: 68,
      category: 'Nature',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 9,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 98,
      discountPercentage: 11.84,
      rating: 4.57,
      size: '40x40',
      stock: 96,
      category: 'Romantic',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 10,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 117,
      discountPercentage: 6.22,
      rating: 4.46,
      size: '50x50',
      stock: 89,
      category: 'Space',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 11,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 96,
      discountPercentage: 8.4,
      rating: 4.32,
      size: '40x40',
      stock: 65,
      category: 'Urban',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 12,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 84,
      discountPercentage: 15.71,
      rating: 4,
      size: '30x30',
      stock: 52,
      category: 'Characters',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 13,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 95,
      discountPercentage: 8.19,
      rating: 4.64,
      size: '40x40',
      stock: 61,
      category: 'Abstract',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 14,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 76,
      discountPercentage: 15.65,
      rating: 4.31,
      size: '30x30',
      stock: 114,
      category: 'Nature',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 15,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 102,
      discountPercentage: 10.97,
      rating: 4.71,
      size: '40x40',
      stock: 105,
      category: 'Romantic',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 16,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 122,
      discountPercentage: 13.35,
      rating: 4.85,
      size: '50x50',
      stock: 110,
      category: 'Space',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 17,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 98,
      discountPercentage: 4.13,
      rating: 4.52,
      size: '40x40',
      stock: 78,
      category: 'Urban',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 18,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 83,
      discountPercentage: 13.15,
      rating: 4.61,
      size: '30x30',
      stock: 88,
      category: 'Characters',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 19,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 121,
      discountPercentage: 10.68,
      rating: 4.42,
      size: '50x50',
      stock: 54,
      category: 'Abstract',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 20,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 118,
      discountPercentage: 16.99,
      rating: 4.06,
      size: '50x50',
      stock: 140,
      category: 'Nature',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 21,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 102,
      discountPercentage: 15.99,
      rating: 4.12,
      size: '40x40',
      stock: 65,
      category: 'Romantic',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 22,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 120,
      discountPercentage: 7.04,
      rating: 4.38,
      size: '50x50',
      stock: 140,
      category: 'Space',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 23,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 97,
      discountPercentage: 20.99,
      rating: 4.79,
      size: '40x40',
      stock: 23,
      category: 'Urban',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
    {
      id: 24,
      title: 'Lorem Ipsum',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl sem, hendrerit vitae convallis sed, interdum nec risus.',
      price: 125,
      discountPercentage: 1.99,
      rating: 4.96,
      size: '50x50',
      stock: 2,
      category: 'Characters',
      images: ['assets/images/temp-painting.png', 'assets/images/temp-painting.png'],
    },
  ],
};

export default posters;
