const posters = {
  products: [
    {
      id: 1,
      title: 'Candles of Light',
      description:
        'Bold geometric shapes rendered in a range of bright colors. This dynamic work of art that showcases the energy and excitement of a bustling city skyline.',
      price: 82,
      discountPercentage: 12,
      rating: 4.73,
      size: '40x40',
      stock: 94,
      category: 'Abstract',
      images: ['assets/images/abstract-01a.jpg', 'assets/images/abstract-01b.jpg', 'assets/images/abstract-01c.jpg'],
    },
    {
      id: 2,
      title: 'Peaceful Flow',
      description:
        'Serene and peaceful depiction of nature at its finest. This artwork conveys a sense of escape, inviting us to imagine ourselves on this idyllic, unspoiled island.',
      price: 103,
      discountPercentage: 18,
      rating: 4.49,
      size: '50x50',
      stock: 34,
      category: 'Nature',
      images: ['assets/images/nature-01a.jpg', 'assets/images/nature-01b.jpg', 'assets/images/nature-01c.jpg'],
    },
    {
      id: 3,
      title: 'Epic Selfie',
      description:
        'Taking a well-deserved break from the galaxy wars. This unusual piece of art will become a real treasure for any Star Wars collector, are you one of them?',
      price: 61,
      discountPercentage: 15,
      rating: 4.15,
      size: '30x30',
      stock: 36,
      category: 'Characters',
      images: [
        'assets/images/characters-02a.jpg',
        'assets/images/characters-02b.jpg',
        'assets/images/characters-02c.jpg',
      ],
    },
    {
      id: 4,
      title: 'Daydreamer',
      description:
        'An exciting visual story of a unique space adventurer. A beautiful and tender work of art that conveys the joy of weightlessness and the beauty of the cosmos.',
      price: 87,
      discountPercentage: 17,
      rating: 4.33,
      size: '40x40',
      stock: 123,
      category: 'Space',
      images: ['assets/images/space-01a.jpg', 'assets/images/space-01b.jpg', 'assets/images/space-01c.jpg'],
    },
    {
      id: 5,
      title: 'Old Times',
      description:
        'The autumn sun casts a warm glow over a charming town. A cozy atmosphere that truly makes the house a home, providing you with comfort and relaxation.',
      price: 76,
      discountPercentage: 10,
      rating: 4.23,
      size: '30x30',
      stock: 32,
      category: 'Urban',
      images: ['assets/images/urban-01a.jpg', 'assets/images/urban-01b.jpg', 'assets/images/urban-01c.jpg'],
    },
    {
      id: 6,
      title: 'Reflective G.',
      description:
        'Solitary Gandalf basking in the breathtaking landscape. This piece of art was created for the real connoisseurs, able to appreciate its majesty and power.',
      price: 95,
      discountPercentage: 11,
      rating: 5,
      size: '40x40',
      stock: 83,
      category: 'Characters',
      images: [
        'assets/images/characters-01a.jpg',
        'assets/images/characters-01b.jpg',
        'assets/images/characters-01c.jpg',
      ],
    },
    {
      id: 7,
      title: 'Vibrant Life',
      description:
        'A blur of bright hues, blending together in a chaotic dance. The vibrant and pulsing energy of the city on this poster is palpable, as if it were alive.',
      price: 107,
      discountPercentage: 4,
      rating: 4.62,
      size: '50x50',
      stock: 50,
      category: 'Urban',
      images: ['assets/images/urban-02a.jpg', 'assets/images/urban-02b.jpg', 'assets/images/urban-02c.jpg'],
    },
    {
      id: 8,
      title: 'That Night',
      description:
        'A couple lost in moment on the shore of a peaceful lake. This piece of art reminds us of the importance of living in the moment, enjoying the little things aroung us.',
      price: 79,
      discountPercentage: 15,
      rating: 4.75,
      size: '30x30',
      stock: 36,
      category: 'Romantic',
      images: ['assets/images/romantic-01a.jpg', 'assets/images/romantic-01b.jpg', 'assets/images/romantic-01c.jpg'],
    },
    {
      id: 9,
      title: 'For the Lifetime',
      description:
        'A story of nothing but real love and happiness. This piece of art is going to surround your life and your house with the simple beauty of true feelings.',
      price: 111,
      discountPercentage: 4,
      rating: 5,
      size: '50x50',
      stock: 50,
      category: 'Romantic',
      images: ['assets/images/romantic-02a.jpg', 'assets/images/romantic-02b.jpg', 'assets/images/romantic-02c.jpg'],
    },
    {
      id: 10,
      title: 'Flower Dance',
      description:
        'Soft petals of light, dancing and swirling all together. These delicate shapes and hues will create a unique atmosphere of beauty and wonder in any room.',
      price: 74,
      discountPercentage: 15,
      rating: 4.15,
      size: '30x30',
      stock: 36,
      category: 'Abstract',
      images: ['assets/images/abstract-02a.jpg', 'assets/images/abstract-02b.jpg', 'assets/images/abstract-02c.jpg'],
    },
    {
      id: 11,
      title: 'Hidden Gem',
      description:
        'High in the mountains, where the air is clear and cold. This artwork is a perfect getaway for your mind and soul: a place where you can leave your troubles behind.',
      price: 94,
      discountPercentage: 18,
      rating: 4.69,
      size: '40x40',
      stock: 34,
      category: 'Nature',
      images: ['assets/images/nature-03a.jpg', 'assets/images/nature-03b.jpg', 'assets/images/nature-03c.jpg'],
    },
    {
      id: 12,
      title: 'Atmosphere',
      description:
        'Braving the unknown in search of adventure and discovery. This solitary figure in the midst of another galaxy inspires us to reach for the stars and chase our dreams.',
      price: 64,
      discountPercentage: 15,
      rating: 4.33,
      size: '30x30',
      stock: 52,
      category: 'Space',
      images: ['assets/images/space-04a.jpg', 'assets/images/space-04b.jpg', 'assets/images/space-04c.jpg'],
    },
    {
      id: 13,
      title: 'Endless Place',
      description:
        'A beauty that stretches out as far as the eye can see. This artwork transports you in the midst of this field, surrounded by the natural beauty of the world.',
      price: 96,
      discountPercentage: 9,
      rating: 4.64,
      size: '40x40',
      stock: 61,
      category: 'Nature',
      images: ['assets/images/nature-02a.jpg', 'assets/images/nature-02b.jpg', 'assets/images/nature-02c.jpg'],
    },
    {
      id: 14,
      title: 'Fashionista',
      description:
        'The power of self-expression through fashion. This stylish and modern fashion collage is for those who want to make a statement with her personal style.',
      price: 106,
      discountPercentage: 17,
      rating: 4.89,
      size: '50x50',
      stock: 114,
      category: 'Abstract',
      images: ['assets/images/abstract-04a.jpg', 'assets/images/abstract-04b.jpg', 'assets/images/abstract-04c.jpg'],
    },
    {
      id: 15,
      title: 'Hopeful Heart',
      description:
        'A scene of innocent wonder and true romance. This piece of art represents the promise of new beginnings and the possibility of infinite love.',
      price: 92,
      discountPercentage: 10,
      rating: 4.71,
      size: '40x40',
      stock: 105,
      category: 'Romantic',
      images: ['assets/images/romantic-03a.jpg', 'assets/images/romantic-03b.jpg', 'assets/images/romantic-03c.jpg'],
    },
    {
      id: 16,
      title: 'Perfect Place',
      description:
        'An idyllic place shining brightly in the clear daylight. An artwork where one can escape the stresses of the world and find peace in the simple pleasures of life.',
      price: 68,
      discountPercentage: 13,
      rating: 4.62,
      size: '30x30',
      stock: 110,
      category: 'Nature',
      images: ['assets/images/nature-05a.jpg', 'assets/images/nature-05b.jpg', 'assets/images/nature-05c.jpg'],
    },
    {
      id: 17,
      title: 'Sunrise City',
      description:
        'The promise of a new day and new possibilities. This poster inspires us to chase our dreams and to embrace the limitless potential of the world around us.',
      price: 122,
      discountPercentage: 21,
      rating: 4.57,
      size: '50x50',
      stock: 110,
      category: 'Urban',
      images: ['assets/images/urban-05a.jpg', 'assets/images/urban-05b.jpg', 'assets/images/urban-05c.jpg'],
    },
    {
      id: 18,
      title: 'MarshmaLove',
      description:
        'The Marshmallow Man as you have ever seen him. This funny artwork of will fill your day with pure enjoyment and relaxation, bringing a smile to your face.',
      price: 73,
      discountPercentage: 3,
      rating: 4.15,
      size: '30x30',
      stock: 88,
      category: 'Characters',
      images: [
        'assets/images/characters-04a.jpg',
        'assets/images/characters-04b.jpg',
        'assets/images/characters-04c.jpg',
      ],
    },
    {
      id: 19,
      title: 'Star Shower',
      description:
        'Twinkling and parkling like diamonds in the darkness. This piece of art is a place of mystery and wonder, where anything seems possible and the imagination can run wild.',
      price: 121,
      discountPercentage: 12,
      rating: 4.42,
      size: '50x50',
      stock: 54,
      category: 'Space',
      images: ['assets/images/space-03a.jpg', 'assets/images/space-03b.jpg', 'assets/images/space-03c.jpg'],
    },
    {
      id: 20,
      title: 'Bright Journey',
      description:
        'A vibrant and playful journey towards something new. It invites us to explore new horizons and embrace our creativity, following our dreams wherever they may lead.',
      price: 98,
      discountPercentage: 16,
      rating: 4.06,
      size: '40x40',
      stock: 65,
      category: 'Abstract',
      images: ['assets/images/abstract-03a.jpg', 'assets/images/abstract-03b.jpg', 'assets/images/abstract-03c.jpg'],
    },
    {
      id: 21,
      title: 'Joyful Game',
      description:
        'A scene of real togetherness and fellowship. Join these joy and excitement of spending time with these group of Mandalorians playing board games all together.',
      price: 112,
      discountPercentage: 13,
      rating: 4.12,
      size: '50x50',
      stock: 140,
      category: 'Characters',
      images: [
        'assets/images/characters-03a.jpg',
        'assets/images/characters-03b.jpg',
        'assets/images/characters-03c.jpg',
      ],
    },
    {
      id: 22,
      title: 'Sleepless Night',
      description:
        "When the romance of the night comes alive. It's a scene of endless possibility, where anything can happen and the world is yours for the taking.",
      price: 70,
      discountPercentage: 7,
      rating: 4.38,
      size: '30x30',
      stock: 140,
      category: 'Urban',
      images: ['assets/images/urban-03a.jpg', 'assets/images/urban-03b.jpg', 'assets/images/urban-03c.jpg'],
    },
    {
      id: 23,
      title: 'Exploring Souls',
      description:
        'Being lost together in their own world. A scene of true romance, where two people are united by their love and their desire to experience the world together.',
      price: 97,
      discountPercentage: 20,
      rating: 4.71,
      size: '40x40',
      stock: 23,
      category: 'Romantic',
      images: ['assets/images/romantic-06a.jpg', 'assets/images/romantic-06b.jpg', 'assets/images/romantic-06c.jpg'],
    },
    {
      id: 24,
      title: 'Reflection',
      description:
        'Boundless curiosity and desire to explore the unknown. A breathtaking artwork, a reminder of the vastness of the universe and the endless possibilities it holds.',
      price: 75,
      discountPercentage: 1,
      rating: 4.35,
      size: '30x30',
      stock: 14,
      category: 'Space',
      images: ['assets/images/space-06a.jpg', 'assets/images/space-06b.jpg', 'assets/images/space-06c.jpg'],
    },
    {
      id: 25,
      title: 'That Color',
      description:
        'Painting the life with streaks of gold and purple. A piece of art of pure beauty and romance, where the natural world puts on a show of unparalleled splendor.',
      price: 77,
      discountPercentage: 7,
      rating: 4.76,
      size: '30x30',
      stock: 4,
      category: 'Nature',
      images: ['assets/images/nature-07a.jpg', 'assets/images/nature-07b.jpg', 'assets/images/nature-07c.jpg'],
    },
    {
      id: 26,
      title: 'True Story',
      description:
        "Being wrapped in each other's arms. It's a scene of true love, support and devotion, and one that inspires us all to hold on to the people we love most.",
      price: 86,
      discountPercentage: 19,
      rating: 4.91,
      size: '50x50',
      stock: 5,
      category: 'Characters',
      images: [
        'assets/images/characters-07a.jpg',
        'assets/images/characters-07b.jpg',
        'assets/images/characters-07c.jpg',
      ],
    },
    {
      id: 27,
      title: 'Waves of Life',
      description:
        'That feeling of endless movement and energy. This piece of art invites us to look beyond the surface and explore the hidden meanings within the art.',
      price: 99,
      discountPercentage: 18,
      rating: 4.56,
      size: '40x40',
      stock: 2,
      category: 'Abstract',
      images: ['assets/images/abstract-05a.jpg', 'assets/images/abstract-05b.jpg', 'assets/images/abstract-05c.jpg'],
    },
    {
      id: 28,
      title: 'Rainy Thoughts',
      description:
        'Taking shelter from the sudden rain. A romantic scene of of quiet and intimate connection that will bring beauty and romance in your house.',
      price: 78,
      discountPercentage: 5,
      rating: 4.46,
      size: '30x30',
      stock: 2,
      category: 'Romantic',
      images: ['assets/images/romantic-04a.jpg', 'assets/images/romantic-04b.jpg', 'assets/images/romantic-04c.jpg'],
    },
    {
      id: 29,
      title: 'Sky Music',
      description:
        'Magical and otherworldly dancing of light. This artwork captures the magic of the natural world, and inspires us all to look up at the sky and dream.',
      price: 125,
      discountPercentage: 6,
      rating: 4.11,
      size: '50x50',
      stock: 26,
      category: 'Space',
      images: ['assets/images/space-05a.jpg', 'assets/images/space-05b.jpg', 'assets/images/space-05c.jpg'],
    },
    {
      id: 30,
      title: 'Stranger Nights',
      description:
        'That sense of adventure and mysterious freedom. We wish you less stranger things at your life, but this artwork is a treasure for a Netflix fan',
      price: 93,
      discountPercentage: 2,
      rating: 4.06,
      size: '40x40',
      stock: 15,
      category: 'Characters',
      images: [
        'assets/images/characters-05a.jpg',
        'assets/images/characters-05b.jpg',
        'assets/images/characters-05c.jpg',
      ],
    },
    {
      id: 31,
      title: 'Promenade',
      description:
        'Simple pleasures of life and small-town charm. This cozy artwork invites us to seek out the beauty and romance of the world around us.',
      price: 60,
      discountPercentage: 11,
      rating: 4.57,
      size: '30x30',
      stock: 12,
      category: 'Urban',
      images: ['assets/images/urban-04a.jpg', 'assets/images/urban-04b.jpg', 'assets/images/urban-04c.jpg'],
    },
    {
      id: 32,
      title: 'True Self',
      description:
        'Warmth, kindness, and generosity. This piece of art captures the essence of love and compassion, and inspires us all to open our hearts.',
      price: 92,
      discountPercentage: 10,
      rating: 4.13,
      size: '40x40',
      stock: 2,
      category: 'Romantic',
      images: ['assets/images/romantic-05a.jpg', 'assets/images/romantic-05b.jpg', 'assets/images/romantic-05c.jpg'],
    },
  ],
};

export default posters;
